### ISSUE TITLE
Build fails for DART-MX6

### ISSUE THREAD

**Issue by Klavishnik** [varigit/variscite-bsp-platform#20]
MACHINE=var-som-mx6 DISTRO=fslc-xwayland source ./setup-environment build 
bitbake core-image-base

Traceback (most recent call last):
  File "/home/user/var-fslc-yocto/sources/poky/bitbake/bin/bitbake", line 19, in <module>
    import bb
  File "/home/user/var-fslc-yocto/sources/poky/bitbake/lib/bb/__init__.py", line 75, in <module>
    import bb.msg
  File "/home/user/var-fslc-yocto/sources/poky/bitbake/lib/bb/msg.py", line 19, in <module>
    import bb.event
  File "/home/user/var-fslc-yocto/sources/poky/bitbake/lib/bb/event.py", line 22, in <module>
    import bb.compat
  File "/home/user/var-fslc-yocto/sources/poky/bitbake/lib/bb/compat.py", line 7, in <module>
    from collections import MutableMapping, KeysView, ValuesView, ItemsView, OrderedDict
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

The error is related to the Python version. If you use python3.7 (+python3.7-distutils), everything works, but is it possible to update the repository?"

**Comment by varigigi** [comment]
Hi @Klavishnik,
you are supposed to use the Ubuntu version reported in the [wiki](https://variwiki.com/index.php?title=VAR-SOM-MX6) for the Yocto BSP you selected.
Latest BSP for VAR-SOM-MX6 is based on [Yocto Dunfell](https://variwiki.com/index.php?title=VAR-SOM-MX6_Yocto&release=RELEASE_DUNFELL_V1.1_VAR-SOM-MX6) and has been validated by the community only up to Ubuntu 20.04 (featuring python 3.8).
My best suggestion is to keep the alignment with community setup for the target BSP version.
For further support, please reach us to [Variscite Customer Portal](https://varisciteportal.axosoft.com/login).
Thanks
Best Regards
Pier
